version: '3'
services:
  # mongodb
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always

  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
  # db rest api
  db-rest-api:
    image: db-rest-api
    build:
      context: ./db-rest-api
      dockerfile: Dockerfile
    container_name: db-rest-api
    ports:
      - "9000:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - FIXTURES_DIR=fixtures
    volumes:
      - ./fixtures:/usr/src/app/fixtures:z
    depends_on:
      - db
    restart: always

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile-dev
    container_name: gateway
    volumes:
      - /tmp/gateway/npm-cache:/root/.npm:z
      - ./gateway/src:/usr/src/app/src:z
      - ./gateway/public:/usr/src/app/public:z
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    depends_on:
      - rabbit
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"

  video-upload:
    image: video-upload
    build:
      context: ./video-upload
      dockerfile: Dockerfile-dev
    container_name: video-upload
    volumes:
      - /tmp/video-upload/npm-cache:/root/.npm:z
      - ./video-upload/src:/usr/src/app/src:z
      - ./video-upload/uploads:/usr/src/app/uploads:z
    ports:
      - "4004:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    depends_on:
      - rabbit
    restart: "no"

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile-dev
    container_name: video-storage
    volumes:
      - /tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src:/usr/src/app/src:z
    ports:
      - "4005:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=ssystrg
      - STORAGE_ACCESS_KEY=fgJqZz3YOTFvIDmRSbwy10baV84Vy6ya1xE0qd3p1ruTcgTmwGoKJCS1yIiAFSpDk0rR8r86qo/S+AStSAejXQ==
    restart: "no"

  metadata:
    image: metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile-dev
    container_name: metadata
    volumes:
      - /tmp/metadata/npm-cache:/root/.npm:z
      - ./metadata/src:/usr/src/app/src:z
    ports:
      - "4006:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=metadata
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"
  # recommendations:
  #   image: recommendations
  #   build:
  #     context: ./recommendations
  #     dockerfile: Dockerfile-dev
  #   container_name: recommendations
  #   volumes:
  #     - /tmp/recommendations/npm-cache:/root/.npm:z
  #     - ./recommendations/src:/usr/src/app/src:z
  #   ports:
  #     - "4004:80"
  #   environment:
  #     - PORT=80
  #     - RABBIT=amqp://guest:guest@rabbit:5672
  #     - DBHOST=mongodb://db:27017
  #     - DBNAME=recommendations
  #     - NODE_ENV=development

  #   depends_on:
  #     - db
  #     - rabbit
  #   restart: "no"
